# <center>**Đề tài: Dự đoán khả năng khách hàng đăng ký gửi tiền có kỳ hạn**<center>

Sinh viên thực hiện:
- **Trần Quốc Hoàng (3123580015)**
- **Trần Chí Vỹ (3123580065)**
- **Phan Trần Hữu Tấn (3123580042)**

Giảng viên hướng dẫn: **TS. Đỗ Như Tài**

## **Tổng quan về đề tài**

### **Lý do chọn đề tài**

Trong bối cảnh cạnh tranh gay gắt của thị trường tài chính hiện đại, các tổ chức ngân hàng không ngừng tìm kiếm giải pháp để tối ưu hóa hiệu quả các chiến dịch Marketing trực tiếp (Direct Marketing). Sản phẩm tiền gửi có kỳ hạn (Term Deposit) là một nguồn vốn quan trọng, nhưng việc tiếp cận và thuyết phục khách hàng tiềm năng là một thách thức lớn.

Thực tế cho thấy, việc triển khai các chiến dịch tiếp thị trên diện rộng thường dẫn đến **tỷ lệ chuyển đổi thấp** và **lãng phí nguồn lực** đáng kể, thể hiện qua số lượng lớn các cuộc gọi được thực hiện đến những khách hàng không có nhu cầu. Do đó, nhu cầu chuyển đổi từ phương pháp tiếp thị đại trà sang **chiến lược tiếp thị mục tiêu (Targeted Marketing)** dựa trên dữ liệu là vô cùng cấp thiết. Bằng cách tận dụng các dữ liệu lịch sử về khách hàng và chiến dịch, ngân hàng có thể xây dựng các mô hình dự đoán và phân khúc để nhận diện chính xác đối tượng cần nhắm đến.

Nghiên cứu này ra đời nhằm mục đích khai thác sức mạnh của **Học máy (Machine Learning)** và **Khai phá dữ liệu (Data Mining)** để phân tích sâu bộ dữ liệu marketing của ngân hàng. Mục tiêu là xây dựng một **mô hình dự đoán đáng tin cậy** có khả năng xác định xác suất đăng ký thành công của từng khách hàng, từ đó tạo ra lợi thế cạnh tranh thông qua việc **tối ưu hóa quy trình ra quyết định và phân bổ nguồn lực**. Nghiên cứu sẽ góp phần giảm chi phí cho các cuộc gọi lãng phí (False Positives) và tối đa hóa lợi nhuận bằng cách tập trung nguồn lực tiếp thị vào nhóm khách hàng tiềm năng cao nhất.

### **Giới thiệu về bộ dữ liệu**
Bộ dữ liệu này liên quan đến các chiến dịch tiếp thị trực tiếp (qua điện thoại) của một tổ chức tài chính - ngân hàng tại Bồ Đào Nha. Các chiến dịch thường yêu cầu nhân viên tiếp thị phải liên lạc nhiều lần với cùng một khách hàng để xác định xem sản phẩm (khoản tiền gửi có kỳ hạn của ngàn hàng) có được đăng ký hay không. Trong bài này, chúng tôi sẽ sử dụng file dữ liệu có tên là bank-additional-full.csv (41188 dòng và 21 cột).

### **Các đặc trưng (cột) bên trong dataset**

#### Dữ liệu khách hàng ngân hàng:
- **age**: tuổi (số)
- **job**: loại công việc (chuỗi)
- **marital**: tình trạng hôn nhân (chuỗi)
- **ducation**: trình độ học vấn (chuỗi)
- **default**: có tín dụng mặc định không? (chuỗi)
- **housing**: có khoản vay nhà ở không? (chuỗi)
- **loan**: có khoản vay cá nhân không? (chuỗi)

#### Liên quan đến liên hệ cuối cùng của chiến dịch hiện tại:
- **contact**: loại hình liên lạc (chuỗi)
- **month**: tháng liên hệ cuối cùng trong năm (chuỗi)
- **day_of_week**: ngày liên hệ cuối cùng trong tuần (chuỗi)
- **duration**: thời lượng liên hệ cuối cùng, tính bằng giây (số).

#### Các thuộc tính khác:
- **campaign**: số lượng liên hệ được thực hiện trong chiến dịch này cho khách hàng này (số)
- **pdays**: số ngày đã trôi qua sau khi khách hàng được liên hệ lần cuối từ một chiến dịch trước đó (số; 999 nghĩa là chưa được liên hệ)
- **previous**: số lượng liên hệ được thực hiện trước chiến dịch này cho khách hàng này (số)
- **poutcome**: kết quả của chiến dịch tiếp thị trước đó (chuỗi)

#### Các thuộc tính bối cảnh kinh tế và xã hội:
- **emp.var.rate**: tỷ lệ thay đổi việc làm - chỉ số hàng quý (số)
- **cons.price.idx**: chỉ số giá tiêu dùng - chỉ số hàng tháng (số)
- **cons.conf.idx**: chỉ số niềm tin tiêu dùng - chỉ số hàng tháng (số)
- **euribor3m**: lãi suất Euribor 3 tháng - chỉ số hàng ngày (số)
- **nr.employed**: số lượng nhân viên - chỉ số hàng quý (số)

#### Biến đầu ra (mục tiêu):
- **y**: khách hàng có đăng ký tiền gửi có kỳ hạn không? (chuỗi: 'yes', 'no')

Nguồn dữ liệu: [Bank Marketing - UCI Machine Learning Repository](https://archive.ics.uci.edu/dataset/222/bank+marketing) on UCI.

### **Câu hỏi nghiên cứu và mục tiêu phân tích**

#### **Câu hỏi nghiên cứu**
- 1. Những yếu tố nào (nhân khẩu học, kinh tế vĩ mô, lịch sử liên hệ) là quan trọng nhất ảnh hưởng đến quyết định đăng ký tiền gửi có kỳ hạn của khách hàng?
- 2. Mô hình Học máy có thể dự đoán chính xác khách hàng nào sẽ đồng ý (y = yes) với mức độ tin cậy và hiệu suất (ví dụ: F1-score) là bao nhiêu?
- 3. Độ tuổi nào có khả năng gửi tiền có kỳ hạn cao nhất và điều gì tác động tới nó?
- 4. Khách hàng có thể được phân nhóm (segment) thành các cụm đặc trưng riêng biệt dựa trên hồ sơ và hành vi của họ không?  
- 5. Cần có những chiến lược tiếp thị khác biệt nào cho từng cụm để tối ưu hóa hiệu quả chuyển đổi?

#### **Mục tiêu phân tích để làm rõ câu hỏi nghiên cứu**

1. **Tiền xử lý và phân tích khám phá dữ liệu (EDA):** Xử lý các vấn đề dữ liệu như mất cân bằng lớp, giá trị unknown và biến rò rỉ dữ liệu (`duration`) để chuẩn bị dữ liệu cho bước mô hình hóa.

2. **Xây dựng mô hình dự đoán (Classification):** Áp dụng và so sánh hiệu suất của nhiều thuật toán học máy khác nhau (Logistic Regression, Random Forest, LightGBM, XGBoost) để tìm ra mô hình tối ưu nhất trong việc nhận diện khách hàng có tiềm năng cao đăng ký sản phẩm.

3. **Xây dựng mô hình phân cụm (Clustering):** Sử dụng các mô hình phân cụm để phân khúc khách hàng, từ đó xác định chân dung rõ ràng của các nhóm tiềm năng (ví dụ: cụm có tỷ lệ thành công cao nhất), giúp đội ngũ Marketing cá nhân hóa thông điệp và kênh tiếp cận.

Kết quả của phân tích này không chỉ cung cấp một mô hình dự đoán mạnh mẽ mà còn đưa ra các **khuyến nghị chiến lược** trực tiếp, đảm bảo rằng nguồn lực tiếp thị được phân bổ hiệu quả nhất, giúp tăng **tỷ suất hoàn vốn (ROI)** cho các chiến dịch trong tương lai.

---

# **1. Kiểm tra thông tin của bộ dữ liệu**
Ở phần này chúng ta sẽ chỉ kiểm tra qua các thông tin cơ bản của dữ liệu.

In [17]:
# Import các thư viện cơ bản
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore',category=FutureWarning)
warnings.filterwarnings('ignore',category=UserWarning)
df = pd.read_csv(r"C:\Users\qhoan\.vscode\Coding\Python\Data Science\Data Mining Solo\Final-Group-Project\data\bank-additional-full.csv", sep = ';')
print(df.shape)

(41188, 21)

## **1.1. Thông tin cơ bản của bộ dữ liệu**

In [18]:
# Hiển thị 5 dòng đầu của dữ liệu
df.head(5).T

,0,1,2,3,4
age,56,57,37,40,56
job,housemaid,services,services,admin.,services
marital,married,married,married,married,married
education,basic.4y,high.school,high.school,basic.6y,high.school
default,no,unknown,no,no,no
housing,no,no,yes,no,no
loan,no,no,no,no,yes
contact,telephone,telephone,telephone,telephone,telephone
month,may,may,may,may,may
day_of_week,mon,mon,mon,mon,mon
duration,261,149,226,151,307
campaign,1,1,1,1,1
pdays,999,999,999,999,999
previous,0,0,0,0,0
poutcome,nonexistent,nonexistent,nonexistent,nonexistent,nonexistent
emp.var.rate,1.1,1.1,1.1,1.1,1.1
cons.price.idx,93.994,93.994,93.994,93.994,93.994
cons.conf.idx,-36.4,-36.4,-36.4,-36.4,-36.4
euribor3m,4.857,4.857,4.857,4.857,4.857
nr.employed,5191.0,5191.0,5191.0,5191.0,5191.0
y,no,no,no,no,no

In [19]:
# Thay "." bằng "_" cho các tên cột
df.columns = df.columns.str.replace(".", "_")

In [20]:
# Thông tin cơ bản của dữ liệu
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp_var_rate    41188 non-null  float64
 16  cons_price_idx  41188 non-null  float64
 17  cons_conf_idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr_employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [21]:
# Hiển thị tên cột (object) và các giá trị độc nhất trong nó
for col in df.columns:
    if df[col].dtype == 'object':
        print(f'\nTên của cột là: ({col}) và các giá trị độc nhất trong nó bao gồm: {df[col].unique()}')

Tên của cột là: (job) và các giá trị độc nhất trong nó bao gồm: ['housemaid' 'services' 'admin.' 'blue-collar' 'technician' 'retired'
 'management' 'unemployed' 'self-employed' 'unknown' 'entrepreneur'
 'student']

Tên của cột là: (marital) và các giá trị độc nhất trong nó bao gồm: ['married' 'single' 'divorced' 'unknown']

Tên của cột là: (education) và các giá trị độc nhất trong nó bao gồm: ['basic.4y' 'high.school' 'basic.6y' 'basic.9y' 'professional.course'
 'unknown' 'university.degree' 'illiterate']

Tên của cột là: (default) và các giá trị độc nhất trong nó bao gồm: ['no' 'unknown' 'yes']

Tên của cột là: (housing) và các giá trị độc nhất trong nó bao gồm: ['no' 'yes' 'unknown']

Tên của cột là: (loan) và các giá trị độc nhất trong nó bao gồm: ['no' 'yes' 'unknown']

Tên của cột là: (contact) và các giá trị độc nhất trong nó bao gồm: ['telephone' 'cellular']

Tên của cột là: (month) và các giá trị độc nhất trong nó bao gồm: ['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'mar' 'apr' 'sep']

Tên của cột là: (day_of_week) và các giá trị độc nhất trong nó bao gồm: ['mon' 'tue' 'wed' 'thu' 'fri']

Tên của cột là: (poutcome) và các giá trị độc nhất trong nó bao gồm: ['nonexistent' 'failure' 'success']

Tên của cột là: (y) và các giá trị độc nhất trong nó bao gồm: ['no' 'yes']

In [22]:
# Thống kê cơ bản cho các biến số
df.describe()

,age,duration,campaign,pdays,previous,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed
count,41188.00000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000
mean,40.02406,258.285010,2.567593,962.475454,0.172963,0.081886,93.575664,-40.502600,3.621291,5167.035911
std,10.42125,259.279249,2.770014,186.910907,0.494901,1.570960,0.578840,4.628198,1.734447,72.251528
min,17.00000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.00000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.00000,180.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.00000,319.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.00000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

In [23]:
# Thống kê cơ bản của các biến đặc trưng
df.describe(include='object')

,job,marital,education,default,housing,loan,contact,month,day_of_week,poutcome,y
count,41188,41188,41188,41188,41188,41188,41188,41188,41188,41188,41188
unique,12,4,8,3,3,3,2,10,5,3,2
top,admin.,married,university.degree,no,yes,no,cellular,may,thu,nonexistent,no
freq,10422,24928,12168,32588,21576,33950,26144,13769,8623,35563,36548

## **1.2. Phân tích mô tả ban đầu**